write_files:
- content: |
    [service_eth0]
    Type = ethernet
    IPv4 = 192.168.100.100/255.255.255.0/192.168.100.1
    IPv6 = off
    MAC = 00:15:5d:de:c1:00
    Nameservers = 8.8.8.8,8.8.4.4
    Timeservers = ntp1.jst.mfeed.ad.jp,ntp2.jst.mfeed.ad.jp,ntp3.jst.mfeed.ad.jp
  owner: root:root
  path: /var/lib/connman/eth0.config
  permissions: '0600'
hostname: k3os-server01